bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'keystore.key'
name = 'testAgent'
public_address = 'HcSciC6UmH5duukm7cp4fJc3tbXOabvvpsvvmpeE3z5jxeoavhdwt9Vjzxekdhz'

[[dnas]]
file = '/home/hector/Escritorio/h-wiki-back/dist/h-wiki-back.dna.json'
hash = 'QmRBRuBKfNJy3LELPPUmYGtkR4xBTYJhhCnx2qGjxZCvTR'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'

id = '__H_Wiki'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = '__H_Wiki'

[interfaces.driver]
port = 3400
type = 'websocket'

[logger]
state_dump = false
type = 'debug'

[logger.rules]
rules = []



[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
