bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'testAgent'
name = 'testAgent'
public_address = 'HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
test_agent = true

[[dnas]]
file = '/home/empleado/Escritorio/holo_wiki/dist/holo_wiki.dna.json'
hash = 'QmQKTqX4UwY2RDKt3rvoCd7ksXit1Syg9rXCrFiq2RcqA3'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'wiki'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'wiki'

[interfaces.driver]
port = 8885
type = 'websocket'

[logger]
state_dump = false
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'wss://0.0.0.0:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
